### ISSUE TITLE
Not sure if we should be checking this in?

### ISSUE THREAD

**Issue by joelklabo** [nostr-sdk/nostr-sdk-ios#2]
I'm not sure if this is something that should be in the `.gitignore` or not..

<img width="905" alt="Screenshot 2023-05-21 at 9 41 30 PM" src="https://github.com/nostr-sdk/nostr-sdk-ios/assets/264977/c9c5ca84-2da0-44b1-8fef-5bf2780922e7">

**Comment by tyiu** [comment]
I'm not sure either. It looks like a way to share IDE settings across all developers? Maybe @bryanmontz knows.
