### ISSUE TITLE
Implement NIP-27 Text Note References

### ISSUE THREAD

**Issue by joelklabo** [nostr-sdk/nostr-sdk-ios#90]

**Comment by joelklabo** [comment]
Also implement NIP-08

**Comment by bryanmontz** [comment]
Issue https://github.com/nostr-sdk/nostr-sdk-ios/issues/116 has now been created for NIP-08 (legacy mentions) support.

**Comment by bryanmontz** [comment]
I think this ticket can be closed now. I moved NIP-08 support to a different ticket, and since NIP-27 contains recommendations for how information is *displayed*, I think it can be left up to the implementing application. Agree @tyiu or @joelklabo?

**Comment by tyiu** [comment]
> I think this ticket can be closed now. I moved NIP-08 support to a different ticket, and since NIP-27 contains recommendations for how information is _displayed_, I think it can be left up to the implementing application. Agree @tyiu or @joelklabo?

Agreed.
